version: '2'
services:
  db1:
    build: .
    ports:
     - "27017:27017"
    container_name: db1
  db2:
    build: .
    ports:
     - "27018:27017"
    container_name: db2
  db3:
    build: .
    ports:
     - "27019:27017"
    container_name: db3
  db4:
    build: .
    ports:
     - "27020:27017"
    container_name: db4
  node:
    build: ./node/
    ports:
      - "3000:3000"
    container_name: node
